### PR TITLE
Fix the test target on macOS

### LINKED ISSUE #25: "make test" does not pass through each trace on macOS
`make test` does not pass through each trace. Instead, it just iterate with command prompt.

### PR DESCRIPTION
**Pull request by owlfox**
To fix #25

### CODE REVIEW

**Comment by jserv** [comment]
Mention "macOS" rather than "Mac".

**Comment by owlfox** [comment]
aspell is quite demanding, so I used " Mac OS X" instead lol

**Comment by jserv** [comment]
> aspell is quite demanding, so I used "Mac OS X" instead lol

You can update file `scripts/aspell-pws`.

**Comment by jserv** [comment]
About grammar: https://www.quora.com/Why-is-it-to-make-it-work-not-to-make-it-works

**Comment by owlfox** [comment]
> > aspell is quite demanding, so I used "Mac OS X" instead lol
> 
> You can update file `scripts/aspell-pws`.

Beautifully done!

**Pull request merged**
