### PR TITLE
 Remove duplicated words

### PR DESCRIPTION
**Pull request by Chao-Shun-Cheng**

### CODE REVIEW

**Review by eecheng87 — COMMENTED** [review]
Please also update [checksums](https://github.com/sysprog21/lab0-c/blob/master/scripts/checksums)

**Comment by eecheng87** [comment]
> That means I need to pull another request for updating checksums ?

No, just update in this PR.

**Comment by eecheng87** [comment]
@Chao-Shun-Cheng, using `git rebase -i` to squash these two commits into one.

**Comment by jserv** [comment]
> @eecheng87 , I think these commits are combined. Please check.

We usually say "[squash](https://dictionary.cambridge.org/dictionary/english-chinese-traditional/squash)" rather than "[combine](https://dictionary.cambridge.org/dictionary/english-chinese-traditional/combine)" since the original two commits no longer exist as individual changes.

**Comment by Chao-Shun-Cheng** [comment]
> > @eecheng87 , I think these commits are combined. Please check.
> 
> We usually say "[squash](https://dictionary.cambridge.org/dictionary/english-chinese-traditional/squash)" rather than "[combine](https://dictionary.cambridge.org/dictionary/english-chinese-traditional/combine)" since the original two commits no longer exist as individual changes.

**Pull request merged**
